### ISSUE TITLE
群聊消息错误地显示出了MiraiCode

### ISSUE THREAD

**Issue by NoMathExpectation** [DreamVoid/Chat2QQ#10]
<strong>问题描述</strong>

![U`P$ T DQ7AB03OJC{GSDJ2](https://user-images.githubusercontent.com/85624722/132113197-a1077153-0749-400b-b94d-5845146f5495.png)

<strong>复现方法</strong>

在群里发送消息

<strong>版本类型</strong>

* Minecraft 服务端版本：paper 1.17.1
* MiraiMC 插件版本：1.4 pre-1
* Chat2QQ 插件版本：1.2.2

<strong>服务器日志</strong>

```
无
```

**Comment by DreamVoid** [comment]
Chat2QQ将很快跟进更新，可先使用MiraiMC 1.3.2
