### ISSUE TITLE
增强对PlaceholderAPI的支持

### ISSUE THREAD

**Issue by XXY233** [DreamVoid/Chat2QQ#12]
<strong>功能描述</strong>

绑定了QQ之后，如果服务器重启玩家不在游戏里，从QQ群发消息，用了PlaceholderAPI的占位符会显示为空。

<strong>使用方法</strong>

![QQ截图20210911214252](https://user-images.githubusercontent.com/46647646/132950034-8e85941b-1df3-4543-b729-7850b923d5a7.jpg)
![QQ截图20210911214455](https://user-images.githubusercontent.com/46647646/132950035-45da8e2b-e171-467d-9196-dacc8068945e.jpg)

**Comment by DreamVoid** [comment]
可以考虑使用别的变量比如player_displayname或者使用别的插件提供的变量
这主要是placeholderapi的问题，我也不可能让插件强迫玩家进服
