### ISSUE TITLE
请问Chat2QQ有计划支持BungeeCore吗？

### ISSUE THREAD

**Issue by Jfeng666** [DreamVoid/Chat2QQ#16]
<strong>功能描述</strong>

chat2QQ使用了解了
不过一个服务器需要一个独立的QQ，所以想了解大大有计划和Miral一样支持BungeeCore端的跨服聊天吗。

我的想法如下
类似支持CrossServerChat这类跨服聊天能够将聊天记录记录到bc后台的插件
因为个人不了解BC端是怎样的工作流程

<strong>使用方法</strong>

1. 用户配置chat2QQ对BC跨端聊天插件的识别格式
2. 正则表达式识别成功，按照上述格式，获取%name% %server% %content%的内容，并通过chat2qq配置的机器人QQ和群号转发
3. QQ群有信息，和平时一样，匹配前缀成功，可以转发bc的config.xml中servers包含的服务器列表。

**Comment by DreamVoid** [comment]
有，准备写
