### ISSUE TITLE
关于绑定

### ISSUE THREAD

**Issue by yasdiox** [DreamVoid/Chat2QQ#17]
验证后 用Chat2QQ从群里发给服务器消息时 %player_name%给出的是UUID而不是用户名 Link2QQ也有同样状况

**Comment by DreamVoid** [comment]
请确认你使用的是最新版本的Chat2QQ

**Comment by yasdiox** [comment]
是1.4.1最新版

**Comment by DreamVoid** [comment]
暂时没有计划修复，如有必要可以开新issue。
