### ISSUE TITLE
多个chat2qq集成一个框架

### ISSUE THREAD

**Issue by fffzzl** [DreamVoid/Chat2QQ#20]
<strong>问题描述</strong>

一个bc服务器里有多个子 服务器需安装插件，一个子服务器就需要开启一个miraiMC，导致登陆设备过多，无法多服使用。

<strong>改进建议</strong>

1. 能否在miraiMC中作为转发服务把chat2qq转发到统一的miraiMC进行群聊推送（需跨公网）
2. 每个子服务器的chat2qq转发到统一的miraiMC进行管理（需跨公网）

**Comment by DreamVoid** [comment]
1.6出了HTTP API模式，现有插件很快会做兼容。
