### ISSUE TITLE
事件监听优先级的问题

### ISSUE THREAD

**Issue by lanzhi6** [DreamVoid/Chat2QQ#21]
<strong>问题描述</strong>

emm,前几天我反馈了一下聊天时间被取消的问题,我看到了您的更新,但是问题似乎没有解决。我发现这是您代码中的一个小问题导致的。在事件监听中，监听优先级被设置为了“LOWEST”，但是嘛，根据spigot的 [api文档](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/EventPriority.html) ，“LOWEST”会使得监听在最前面被调用，这使得您的监听在别的插件钱运行，别的插件的取消操作会在您插件之后，或许应该将优先级设为“MONITOR”（纯粹为了监听结果）或者“HIGHEST”（在最后调用决定最终结果），我也不太清楚。总的来说，您的插件以及前置十分有用，帮了我不少，也希望您尽快修复，谢谢！

<strong>复现方法</strong>

1. 无

<strong>版本类型</strong>

* Minecraft 服务端版本：purpur1.18
* MiraiMC 插件版本：1.5.2
* Chat2QQ 插件版本：1.4.2

<strong>服务器日志</strong>

```
无
```

**Comment by lanzhi6** [comment]
对了,这样还可以使得聊天插件的设置可以作用在qq的消息里

**Comment by DreamVoid** [comment]
是我草率了，等一下我发1.5版本会修掉。
