### ISSUE TITLE
你写错了一个代码

### ISSUE THREAD

**Issue by byxiaobai** [DreamVoid/Chat2QQ#24]
<strong>问题描述</strong>

在PlayerJoinListener里，你写对了，但是在/qchat指令里，仍然使用了老的HTTPAPI发送信息，事实上，HTTPAPI的INSTANCE在BC端根本就没有初始化。换句话讲，只能在玩家加入/退出时向群中发送信息，但是指令无法向群中发送信息
![image](https://user-images.githubusercontent.com/26520933/153531269-aaa378a9-453a-4d2c-a26b-33eddf64b41f.png)
![image](https://user-images.githubusercontent.com/26520933/153531304-b20ad1e3-fd00-48ce-bbc7-7ebb4bb666bf.png)
qq：3458571636，希望能联系一下

**Comment by DreamVoid** [comment]
是的，你很聪明，既然你知道问题所在，为什么不尝试开一个PR帮我修复呢
