### ISSUE TITLE
添加控制进出服信息发送频率的选项

### ISSUE THREAD

**Issue by haoenz** [DreamVoid/Chat2QQ#27]
# 功能描述

**需求**
添加控制进出服信息发送频率的选项

**场景**
偶尔玩家会因为种种原因频繁进出服务器，导致进出服务器的消息在QQ群内刷屏。
然而这并不是出于玩家的主观故意，管理员并不能按恶意刷屏直接禁言。

# 使用方法
在config文件中添加一个时间变量用以限制进出服消息转发频率。

_最后顺便一提，issue的模板用markdown而非html来写会不会看起来更清爽一点？_

**Comment by DreamVoid** [comment]
会加
issue模板我打算全换成yaml
