### ISSUE TITLE
mirai-http-api怎么设置

### ISSUE THREAD

**Issue by fffzzl** [DreamVoid/Chat2QQ#30]
<strong>问题描述</strong>

chat2qq支持mirai-http-api后都下载了新版本，miraiMC在velocity上登录qq，chat2qq安装在了1.16.5paper，加载chat2qq需要miraiMC才能加载，并且安装miraiMC后chat2qq里没有mirai-http-api的设置位置，miraiMC也没有详细转发到velocity的miraiMC方法。
我应该怎么样才能在velocity登录miraiMC，剩下多个子服务器使用chat2qq通过mirai-http-api连接到miraiMC上（可能还会跨物理服务器）

<strong>复现方法</strong>

1. velocity安装miraiMC登录qq
2. paper-1.16.5安装chat2qq和miraiMC不登陆qq
3. paper的miraiMC没登陆qq无法发消息到q群，不安装无法启动chat2qq
4. 希望通过http-api传到velocity的miraiMC

<strong>版本类型</strong>

* Minecraft 服务端版本：paper1.16.5
* velocity 版本： 3.1.2-SNAPSHOT
* MiraiMC 插件版本：1.6
* Chat2QQ 插件版本：1.5

**Comment by fffzzl** [comment]
因为有多个子服务器，不可能一个服务器登录一个qq

**Comment by DreamVoid** [comment]
velocity版本暂不支持http api，请等待MiraiMC 1.7
