### ISSUE TITLE
一些消息优化建议?

### ISSUE THREAD

**Issue by From-pErfo** [DreamVoid/Chat2QQ#31]
**功能描述**
一些消息优化建议?

**使用方法**
2. 提取卡片消息内容或屏蔽卡片消息为`[卡片消息]`, 它出现在群公告上
3. 处理换行: `为每个换行前添加n个空格缩进来区分消息`
6. 玩家可使用指令撤回自己使机器人发的上一条消息?
7. 将聊天消息显示在工具栏[那个物品栏上方], _如果能做到或许可以解决消息撤回问题了?_
8. 配置 限制群名片长度
9. 配置 不将消息显示在控制台, 或输出到单独的日志文件[这是Chat2QQ插件的消息吗?]
10. 配置 过滤颜色样式字符, 防止伪造服务器消息? [或许可以通过第3个解决], 主要因为URL带有&符号

**我使用的配置**
始终转发QQ群消息到服务器
服务器消息添加前缀`#`发送到QQ群
群->服务器: `&7[%nick%] %message%`
服务器->群: `[%player%] %message%`

**Comment by DreamVoid** [comment]
1. 做不到，别问为什么
2. 可以
3. 细说，没理解，最好带图
4. 你把玩家的broadcast权限禁了就收不到了
5. #27 
6. 可以
7. 细说，没理解
8. 细说，没理解
9. 可以，另外MiraiMC也会输出消息到控制台，有开关可以关闭，另外你可以为控制台禁用broadcast权限，这样就也收不到了
10. 可以
11. 细说，聊天前缀不能满足你吗

**Comment by From-pErfo** [comment]
嗯... 只是自己的一些想法... [希望我没说错什么..]

```
3. 处理换行:

[名称] 消息
消息
消息
->
[名称] 消息
    消息
    消息
```

```
7. 将消息显示在操作栏[ACTION_BAR]

我不知道这个具体是什么, 但它不会占用聊天栏的空间
```


```
9. 限制群名片长度: 

[玩家名称玩家名称玩家名称玩家名称玩家名称] 消息
->
[玩家名称...] 消息 #限制在n位以内
```
