### ISSUE TITLE
增加群黑名单账号/信息

### ISSUE THREAD

**Issue by RainEffect** [DreamVoid/Chat2QQ#36]
<strong>功能描述</strong>

在Chat2QQ中增加一个群内黑名单列表功能，用于指定部分用户的QQ信息不会转发到mc内（如其他机器人等），以及增加屏蔽前缀/包含内容的列表，屏蔽指定机器人的指令/触发条件。

<strong>使用方法</strong>

1. 

在config.yml中增加以下内容
`bot:`
`  # 群黑名单列表，用于屏蔽群内其他消息 如其他的通用机器人`
`  group-blacklist:`
` `
`    # 启用这个功能`
`    enabled: true`
` `
`    # 需要被屏蔽的账号`
`    account:`
`    - 336****147`
`    - 320****384`
` `
`    # 需要被屏蔽的消息前缀 (忽略大小写)`
`    prefix:`
`    - "@336****147"`
`    - "@320****384"`
`    - "rb"`
`    - "rainbot"`
`    - "@114514****"`
`    - "@256097****"`
`    - "/fb"`
`    - "/fufubot"`
` `
`    # 需要被屏蔽的触发词 (包含在全文中即处理，忽略大小写)`
`    include:`
`    - "嘉然"`
`    - "肖战"`

(以上为未来实装后个人的设置内容，功能限制条件未必齐全，QQ号已屏蔽)

**Comment by DreamVoid** [comment]
你的屏蔽词我喜欢，
你提的功能我会加。

**Comment by RainEffect** [comment]
虽然实际上，屏蔽词是某bot的（笑
![屏蔽词原因图](https://user-images.githubusercontent.com/14258727/161361896-2ae467f2-dca6-4254-b028-1e398c71d948.png)
