### ISSUE TITLE
增加指令使用功能，并进行处理

### ISSUE THREAD

**Issue by RainEffect** [DreamVoid/Chat2QQ#38]
<strong>功能描述</strong>

通过Chat2QQ，在QQ群内直接使用指令，针对手机端不方便进入服务器，也可以快速使用，与Link2QQ联动
注: 命令不会被处理，在QQ内为了和其他bot区分，可能需要增加指定前缀进行

<strong>使用方法</strong>

在config.yml中增加以下内容:
`bot:`
`  # 群指令功能`
`  command-in-group:`
`    # 是否启用`
`    enable: false`
` `
`    # 是否需要绑定后才可以执行命令`
`    bind-enforce: false`
` `
`    # 是否需要前缀`
`    prefix-need: true`
` `
`    # 前缀内容:`
`    prefix:`
`    - "c2m"`
`    - "chat2mc"`
`    - "@336****147"`
` `
`    # 未绑定状态下可执行的指令`
`    unbind-command:`
`    - "list"`
` `
`    # 指定普通用户可使用指令`
`    use-command:`
`    - "msg"`
` `
`    # 指定管理员指令`
`    admin-command:`
`    - "kick"`
`    - "ban"`
`    - "whitelist"`
`    - "qchat"` 我用我自己
` `
`    # 指定管理员账号`
`    admin-account:`
`    - 255****162`
`    - 494***707`

(以上为未来实装后个人的设置内容，功能限制条件未必齐全，QQ号已屏蔽)

**Comment by RainEffect** [comment]
此功能因为要获取指令所返回的信息，可能会比较麻烦，不急

**Comment by DreamVoid** [comment]
我不认为执行指令是一个“聊天插件”应该做的事。
