### ISSUE TITLE
服务器卡顿

### ISSUE THREAD

**Issue by NoMathExpectation** [DreamVoid/Chat2QQ#4]
<strong>问题描述</strong>

发送服务器消息到群里的过程非异步导致服务器卡顿

<strong>复现方法</strong>

1. 

<strong>版本类型</strong>

* Minecraft 服务端版本：paper 1.17.1
* MiraiMC 插件版本：1.3-pre3
* Chat2QQ 插件版本：1.1

<strong>服务器日志</strong>

```
无
```

**Comment by DreamVoid** [comment]
已修复，请使用 1.2.1 版本
