### ISSUE TITLE
对无法进入服务器的用户进行延时处理

### ISSUE THREAD

**Issue by RainEffect** [DreamVoid/Chat2QQ#47]
### 功能描述

RT，经常会有玩家在网络出现波动或验证不完整的情况下加入到服务器，这样多次的反复无疑会对群内聊天产生影响。
包括但不仅有：服务器网络波动，客户端验证不通过，模组信息包传输超时，客户端处理超时…

包括说因为玩家网络波动导致意外退出了服务器重新加入的情况，也可以通过该项进行快速处理。

可以考虑延迟进服信息推送的方式，用于防止出现此类情况。
![游戏内显示](https://user-images.githubusercontent.com/14258727/162628783-b4bd4d26-e14a-41bd-9890-2ed0cd0464b6.png)
![Q群内显示](https://user-images.githubusercontent.com/14258727/162628793-f6222691-851f-4fd1-8816-780da3599b8e.png)

### 使用方法

在config.yml中增加以下内容:

`bot:`
`  # 延迟进服退服消息`
`  delay-join-quit-message:`
`    # 启用这个功能`
`    enable: true`
` `
`    # 进服消息延时 单位:ms`
`    join-delay: 1000`
` `
`    # 退服消息延时 单位:ms`
`    quit-delay: 3000`

### 额外说明

进服消息延时默认为1秒，及进入服务器后如果在1秒内自动退出则不会发送消息至群内，当然这个数值可以针对服务器的不同进行额外调整，如大型模组服可以设定为30秒。

退服消息延时默认为3秒，及退出服务器后如果在3秒内重新进入到服务器则不会发送退出服务器的消息至群内(针对部分模组带自动重连服务器功能)

另外，此类消息延时在用户发出聊天信息时(普遍玩家在进入服务器且正常时才能发送消息)，延时将被强制取缔(发送到群内)，并同时转发聊天信息。

**Comment by DreamVoid** [comment]
https://github.com/DreamVoid/Chat2QQ/issues/27
