### ISSUE TITLE
只有管理员能收到群里的消息

### ISSUE THREAD

**Issue by BaneQQ** [DreamVoid/Chat2QQ#5]
在配置文件里设置了聊天前缀识别
群里说话必须加*  服务器才能收到

但是测试了一下只有管理员能收到这种信息，普通玩家收不到。
看了下chat2qq只有两个权限节点，都给玩家权限组点开了还是不行.

请问是什么原因呢？

**Comment by DreamVoid** [comment]
请描述清楚，比如“管理员”是服务器的管理员还是QQ群的管理员，收到来自群的消息还是来自服务器的消息

**Comment by BaneQQ** [comment]
> 请描述清楚，比如“管理员”是服务器的管理员还是QQ群的管理员，收到来自群的消息还是来自服务器的消息

只有服务器的管理员能收到来自QQ群的消息，服务器的普通玩家收不到

**Comment by DreamVoid** [comment]
请检查是否给予玩家```bukkit.broadcast.user```权限和```bukkit.broadcast```权限，Chat2QQ 本身没有做权限判断，采用了Bukkit的```broadcastMessage```广播聊天消息。上述两个权限节点默认为玩家拥有，如玩家没有这两个权限将无法接收消息。

**Comment by BaneQQ** [comment]
> 请检查是否给予玩家`bukkit.broadcast.user`权限和`bukkit.broadcast`权限，Chat2QQ 本身没有做权限判断，采用了Bukkit的`broadcastMessage`广播聊天消息。上述两个权限节点默认为玩家拥有，如玩家没有这两个权限将无法接收消息。

好的，谢谢，已经解决了，是因为没有这两个权限 :)
