### ISSUE TITLE
适配MiraiMC1.7-pre2的请求

### ISSUE THREAD

**Issue by CCBlueX666** [DreamVoid/Chat2QQ#53]
### 问题描述

在更新MiraiMC至1.7-pre2，由游戏内向外发送正常，由群内向游戏内发送消息无效，Mirai核心可以检测到消息，但是Chat2QQ没有转发

### 复现方法

1. 更新MiraiMC至1.7-pre2
2. 群里发一条消息
3. 检查终端和游戏

### 服务端类型

Bukkit

### 服务端版本

paper-1.18.2-379

### MiraiMC 插件版本

1.7-pre2

### Chat2QQ 插件版本

1.5

### 服务端日志

```text
见额外说明
```

### 额外说明

[latest.log](https://github.com/DreamVoid/Chat2QQ/files/8936691/latest.log)

### 协议

- [X] 我已查阅[常见问题疑难解答](https://wiki.miraimc.dreamvoid.ml/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/Chat2QQ/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by seyink** [comment]
我遇到了相同问题

**Comment by DreamVoid** [comment]
1.7-pre2增加了一个兼容选项，查看更新日志。
1.7正式版发布后相关插件会同步更新。
