### ISSUE TITLE
与link2qq的联动有问题

### ISSUE THREAD

**Issue by msj20080623** [DreamVoid/Chat2QQ#7]
其他发送接收在spigot上都已经解决，但是：
  bind-chat-format: "&6[QQ/%nick%(%qq%)]&r **_%vault_prefix% %player_name% %vault_suffix%_**: %message%"
这几个新变量无法使用
1.16.5 spigot

**Comment by DreamVoid** [comment]
检查是否安装placeholderapi并检查是否安装vault拓展
如需帮助，请参考相关插件帮助
