### ISSUE TITLE
添加消息回复、公告和图片消息支持

### ISSUE THREAD

**Issue by Qian-F** [DreamVoid/Chat2QQ#70]
### 功能描述

对qq群消息回复添加支持，目前回复消息阅读体验差
对群公告和图片类型的群消息提供支持，目前为乱码

### 使用方法

优化阅读体验、消除乱码

**Comment by DreamVoid** [comment]
你想找的是不是 https://github.com/DreamVoid/Chat2QQ/pull/67

**Comment by Qian-F** [comment]
> 你想找的是不是 https://github.com/DreamVoid/Chat2QQ/pull/67

已加入现版本了吗请问

**Comment by Qian-F** [comment]
还有回复阅读体验不佳

**Comment by DreamVoid** [comment]
没有兴趣为非聊天消息提供修复

**Comment by Qian-F** [comment]
> 没有兴趣为非聊天消息提供修复
回复消息不是聊天信息吗

**Comment by Qian-F** [comment]
而且图片也是聊天中常有的事情吧

**Comment by DreamVoid** [comment]
你说图片发出来是乱码，但是图片显示在游戏里只有“[图片]”，哪来的乱码，或者你觉得这个就是乱码？

**Comment by Qian-F** [comment]
> 你说图片发出来是乱码，但是图片显示在游戏里只有“[图片]”，哪来的乱码，或者你觉得这个就是乱码？

哦抱歉那就没有图片的问题  回复和群公告怎么说

**Comment by ApliNi** [comment]
这边有一个添加更多功能的分支, https://github.com/ApliNi/Chat2QQ

**Comment by Qian-F** [comment]
> 这边有一个添加更多功能的分支, https://github.com/ApliNi/Chat2QQ

star了一下  期待更新！ 如果可以内置mirai的话就更好了

**Comment by ApliNi** [comment]
> > 这边有一个添加更多功能的分支, https://github.com/ApliNi/Chat2QQ
> 
> star了一下 期待更新！ 如果可以内置mirai的话就更好了

🎁 https://github.com/ApliNi/Chat2QQ/releases
