### ISSUE TITLE
请兼容1.19.4paper端

### ISSUE THREAD

**Issue by anxge** [DreamVoid/Chat2QQ#74]
### 问题描述

如题，1.19.4paper端无法使用

### 复现方法

1. 游戏内发送文字报错
2. 群内发送文字报错

### 服务端类型

Bukkit

### 服务端版本

Paper-1.19.4

### MiraiMC 插件版本

1.8-pre1

### Chat2QQ 插件版本

1.6 

### 服务端日志

```text
日志过长，已放入补充说明
```

### 额外说明

[latest.log](https://github.com/DreamVoid/Chat2QQ/files/11636936/latest.log)

### 协议

- [X] 我已查阅[常见问题疑难解答](https://wiki.miraimc.dreamvoid.ml/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/Chat2QQ/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
`java.lang.NullPointerException: Cannot invoke "net.mamoe.mirai.contact.Group.sendMessage(net.mamoe.mirai.message.data.Message)" because "this.group" is null`
自行检查机器人是否在群内
