### ISSUE TITLE
请求加入聊天监测

### ISSUE THREAD

**Issue by Syscat20** [DreamVoid/Chat2QQ#8]
<strong>功能描述</strong>

服务器使用了EssentialsX、QuickShop、AuthMe等插件，并且Bot处设置了在游戏内无需前缀也可以向群聊发送消息。
但玩家进入服务器且未登录时、玩家被"/mute"禁言时、玩家按部分插件要求在聊天栏键入数值时，键入的内容都可以被发送到群聊内。
希望可以改进一下，避免出现这种情况。

<strong>使用方法</strong>

1.

**Comment by DreamVoid** [comment]
目前没有计划与此类插件共存，你所描述的情况过于小众，应该**让相关插件取消玩家聊天事件**，而不是让Chat2QQ来主动兼容，Chat2QQ是监听AsyncPlayerChat事件的，其他相关插件完全可以把它们的事件监听提到较高等级，这部分插件的工作性质也决定了它们应该提高监听等级
如果不愿更换插件，请开启聊天前缀功能
