### ISSUE TITLE
将进服消息发送进qq

### ISSUE THREAD

**Issue by Shapaper** [DreamVoid/Chat2QQ#9]
1.将进服退服消息同步qq群（配置文件中可选）
2.在群中发送[.chat2qq list]命令可以自动回复玩家列表（配置文件中可以自由调节，0表示所有玩家都可以使用，1表示管理员/腐竹，2表示仅为腐竹）
3.在【2】的基础上允许在配置文件中配置自定义命令。【如：ping】

**Comment by DreamVoid** [comment]
你所说的功能已经超出Chat2QQ的功能范围了，我认为一款插件应该只专注于一件事，并做好这件事
功能1可以考虑，功能2我打算另开新插件
